export const LIST_RECIPES = 'LIST_RECIPES'

export const AUTHENTICATED = 'AUTHENTICATED'
export const UNAUTHENTICATED = 'UNAUTHENTICATED'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'

export const GETHOUSES = 'GETHOUSES'
export const GETHOUSESID = 'GETHOUSESID'
export const GETHOUSESUSERS = 'GETHOUSESUSERS'
export const PUTHOUSESUSERS = 'PUTHOUSESUSERS'
